/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2026-04-20 17:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class documentVault_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>PawPort | Document Vault</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Updated overall body to use the logo's slate teal for a cohesive background, but lighter */\r\n");
      out.write("        body { \r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; \r\n");
      out.write("            background-color: #E6EDEC; /* A very light tint of the slate teal */\r\n");
      out.write("            margin: 40px; \r\n");
      out.write("            color: #2c3e50; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 1. Remove the main container border and make shadow subtle */\r\n");
      out.write("        .container { \r\n");
      out.write("            max-width: 900px; \r\n");
      out.write("            margin: auto; \r\n");
      out.write("            background: white; \r\n");
      out.write("            padding: 40px; \r\n");
      out.write("            border-radius: 12px; \r\n");
      out.write("            /* Subtle shadow to define without a border */\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.06); \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Update header alignment with your logo */\r\n");
      out.write("        .header-section { \r\n");
      out.write("            display: flex; \r\n");
      out.write("            align-items: center; \r\n");
      out.write("            /* No bottom border here */\r\n");
      out.write("            padding-bottom: 20px; \r\n");
      out.write("            margin-bottom: 30px; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 { \r\n");
      out.write("            margin: 0; \r\n");
      out.write("            font-size: 2.2em; \r\n");
      out.write("            color: #2c3e50; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 2. Style using the signature SLATE TEAL from the logo */\r\n");
      out.write("        .primary-color { color: #4F797D; } /* Pure color from logo background */\r\n");
      out.write("        .primary-bg { background-color: #4F797D; color: white; }\r\n");
      out.write("\r\n");
      out.write("        /* Style the Upload Box to be subtle yet defined, using slate teal tints */\r\n");
      out.write("        .upload-box { \r\n");
      out.write("            background-color: #F0F4F4; /* A lighter tint of slate teal */\r\n");
      out.write("            padding: 25px; \r\n");
      out.write("            border-radius: 10px; \r\n");
      out.write("            margin-bottom: 35px; \r\n");
      out.write("            border: 1px solid #4F797D; /* Using slate teal for a defined border */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .upload-box h3 { margin-top: 0; color: #4F797D; }\r\n");
      out.write("\r\n");
      out.write("        label { \r\n");
      out.write("            font-weight: 600; \r\n");
      out.write("            color: #4F797D; \r\n");
      out.write("            margin-bottom: 5px; \r\n");
      out.write("            display: block; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 3. Style the buttons and accent elements with the MUTED ORANGE from the logo */\r\n");
      out.write("        .btn { \r\n");
      out.write("            background-color: #D28A5D; /* Pure color from logo's compass */\r\n");
      out.write("            color: white; \r\n");
      out.write("            padding: 12px 24px; \r\n");
      out.write("            border: none; \r\n");
      out.write("            border-radius: 6px; \r\n");
      out.write("            cursor: pointer; \r\n");
      out.write("            font-weight: 600; \r\n");
      out.write("            transition: background 0.2s ease; \r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover { background-color: #B2754E; /* A darker, richer orange on hover */ }\r\n");
      out.write("\r\n");
      out.write("        /* Refined table with subtle grid */\r\n");
      out.write("        table { \r\n");
      out.write("            width: 100%; \r\n");
      out.write("            border-collapse: collapse; \r\n");
      out.write("            margin-top: 10px; \r\n");
      out.write("            box-shadow: 0 2px 5px rgba(0,0,0,0.02);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        th, td { \r\n");
      out.write("            padding: 16px 12px; \r\n");
      out.write("            text-align: left; \r\n");
      out.write("            border-bottom: 1px solid #EAECEF; \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Using SLATE TEAL for the table header */\r\n");
      out.write("        th { \r\n");
      out.write("            background-color: #4F797D; \r\n");
      out.write("            color: white; \r\n");
      out.write("            font-weight: 600; \r\n");
      out.write("            text-transform: uppercase; \r\n");
      out.write("            font-size: 0.85em; \r\n");
      out.write("            letter-spacing: 0.05em; \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        tr:last-child td { border-bottom: none; }\r\n");
      out.write("        \r\n");
      out.write("        /* Subtle tag for encrypted status, using slate teal tints */\r\n");
      out.write("        .status-tag { \r\n");
      out.write("            padding: 5px 10px; \r\n");
      out.write("            border-radius: 20px; \r\n");
      out.write("            font-size: 0.85em; \r\n");
      out.write("            font-weight: 500; \r\n");
      out.write("            background: #D5E1E2; /* Slate teal tint */\r\n");
      out.write("            color: #4F797D; /* Slate teal */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Styling links to use the primary SLATE TEAL */\r\n");
      out.write("        a { color: #4F797D; text-decoration: none; font-weight: 500; }\r\n");
      out.write("        a:hover { text-decoration: underline; }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"header-section\">\r\n");
      out.write("        <img src=\"Images/logoWithoutPawPort.png\" alt=\"PawPort Logo\" style=\"height: 60px; margin-right: 20px;\">\r\n");
      out.write("        <h1 class=\"primary-color\">PawPort Document Vault</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <p style=\"color: #6c757d; max-width: 600px; margin-bottom: 30px;\">Securely store and manage your pet's vital records, vaccinations, and certifications.</p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"upload-box\">\r\n");
      out.write("        <h3>Upload a New Document</h3>\r\n");
      out.write("        <form action=\"DocumentVault\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                <label>File Selection (e.g., PDF or Image):</label>\r\n");
      out.write("                <input type=\"file\" name=\"file\" required style=\"border: 1px solid #D1D5DB; padding: 10px; width: calc(100% - 22px); border-radius: 6px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"margin-bottom: 25px;\">\r\n");
      out.write("                <label>Document Category:</label>\r\n");
      out.write("                <select name=\"category\" style=\"border: 1px solid #D1D5DB; padding: 10px; width: 100%; border-radius: 6px; font-size: 1em;\">\r\n");
      out.write("                    <option value=\"Vaccination\">Vaccination Record</option>\r\n");
      out.write("                    <option value=\"License\">City License</option>\r\n");
      out.write("                    <option value=\"Medical\">General Medical</option>\r\n");
      out.write("                    <option value=\"Insurance\">Pet Insurance</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">Upload </button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <h3 class=\"primary-color\" style=\"margin-bottom: 20px;\">Stored Records</h3>\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Document Name</th>\r\n");
      out.write("                <th>Category</th>\r\n");
      out.write("                <th>Date Uploaded</th>\r\n");
      out.write("                <th>Status</th>\r\n");
      out.write("                <th>Action</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Rabies_Cert_Buddy.pdf</td>\r\n");
      out.write("                <td>Vaccination</td>\r\n");
      out.write("                <td>April 16, 2026</td>\r\n");
      out.write("                <td><span class=\"status-tag\">Encrypted</span></td>\r\n");
      out.write("                <td><a href=\"#\">View</a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
